name: CI Backend Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: Set up JDK 17
    #  uses: actions/setup-java@v4
    #  with:
    #    java-version: '17'
    #    distribution: 'temurin'
    #    cache: maven
    - name: Setup JDK17
      run: |
          apt-get update
          apt install -y openjdk-17-jdk
          java -version
          apt install -y maven
          mvn -version
    - name: Build step
      run: mvn clean install
